export const vaccineData = [
  {
    product_category: 'DNA-based',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Australia',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Bangladesh',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Canada',
    count: 2,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Denmark',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Egypt',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Great Britain',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Slovenia',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Sweden',
    count: 2,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Thailand',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Turkey',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '0. Pre-clinical',
    country_name: 'United States',
    count: 3,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '1. Phase I',
    country_name: 'Canada',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '2. Phase II or Combined I/II',
    country_name: 'China',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '2. Phase II or Combined I/II',
    country_name: 'India',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '2. Phase II or Combined I/II',
    country_name: 'Japan',
    count: 1,
  },
  {
    product_category: 'DNA-based',
    clinical_stage: '2. Phase II or Combined I/II',
    country_name: 'South Korea',
    count: 1,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Brazil',
    count: 1,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '0. Pre-clinical',
    country_name: 'China',
    count: 2,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Egypt',
    count: 1,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Japan',
    count: 2,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Thailand',
    count: 1,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Turkey',
    count: 2,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '0. Pre-clinical',
    country_name: 'United States',
    count: 1,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Vietnam',
    count: 1,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '1. Phase I',
    country_name: 'Turkey',
    count: 1,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '2. Phase II or Combined I/II',
    country_name: 'China',
    count: 1,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '2. Phase II or Combined I/II',
    country_name: 'Kazakhstan',
    count: 1,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '3. Phase III',
    country_name: 'Brazil',
    count: 1,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '3. Phase III',
    country_name: 'China',
    count: 2,
  },
  {
    product_category: 'Inactivated virus',
    clinical_stage: '3. Phase III',
    country_name: 'India',
    count: 1,
  },
  {
    product_category: 'Live attenuated virus',
    clinical_stage: '0. Pre-clinical',
    country_name: 'India',
    count: 2,
  },
  {
    product_category: 'Live attenuated virus',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Turkey',
    count: 1,
  },
  {
    product_category: 'Live attenuated virus',
    clinical_stage: '0. Pre-clinical',
    country_name: 'United States',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Bangladesh',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'China',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Egypt',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Finland',
    count: 2,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'France',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Germany',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Great Britain',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'India',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Japan',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Spain',
    count: 2,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Thailand',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'Turkey',
    count: 2,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '0. Pre-clinical',
    country_name: 'United States',
    count: 6,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '1. Phase I',
    country_name: 'Italy',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '1. Phase I',
    country_name: 'United States',
    count: 2,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '3. Phase III',
    country_name: 'Great Britain',
    count: 1,
  },
  {
    product_category: 'Non-replicating viral vector',
    clinical_stage: '3. Phase III',
    country_name: 'Russia',
    count: 2,
  },
];
