language: node_js

node_js:
  - 10.7

cache:
  - npm: true
  - yarn: true

matrix:
  fast_finish: true

install:
  - yarn install
  - npm install -g codecov

script:
  - yarn run test

after_script:
  - codecov
