language: node_js

node_js:
  - 10.7

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

install:
  - npm install
  - npm install -g codecov

script:
  - yarn install
  - yarn run test --debug --no-cache

after_script:
  - codecov
