import Loadable, { LoadableComponent } from 'react-loadable';

export type LoadableRendererProps = {
  onRenderFailure?: Function;
  onRenderSuccess?: Function;
};

type LoadableRendererType = React.ComponentClass<Loadable.CommonOptions & LoadableRendererProps> &
  Loadable.LoadableComponent;

const defaultProps = {
  onRenderFailure() {},
  onRenderSuccess() {},
};

export default function createLoadableRenderer(
  options: Loadable.OptionsWithMap<Loadable.CommonOptions, {}>,
): LoadableComponent {
  /* eslint-disable-next-line babel/new-cap */
  const LoadableRenderer = Loadable.Map(options) as LoadableRendererType;

  // Extends the behavior of LoadableComponent
  // generated by react-loadable
  // to provide post-render listeners
  class CustomLoadableRenderer extends LoadableRenderer {
    componentDidMount() {
      this.afterRender();
    }

    componentDidUpdate() {
      this.afterRender();
    }

    afterRender() {
      const { loaded, loading, error } = this.state;
      const { onRenderFailure, onRenderSuccess } = this.props;
      if (!loading) {
        if (error && onRenderFailure) {
          onRenderFailure(error);
        } else if (loaded && Object.keys(loaded).length > 0 && onRenderSuccess) {
          onRenderSuccess();
        }
      }
    }
  }

  CustomLoadableRenderer.defaultProps = defaultProps;
  CustomLoadableRenderer.preload = LoadableRenderer.preload;

  return CustomLoadableRenderer;
}
