export const GraphConstants = {
  zoom: 1,
  circularConfig: { rotateLabel: true },
  forceConfig: {
    initLayout: 'circular',
    layoutAnimation: true,
  },
  edgeSymbol: ['circle', 'arrow'],
  edgeSymbolSize: [10, 10],
  labelConfig: {
    show: true,
    position: 'right',
    distance: 5,
    rotate: 0,
    offset: [0, 0],
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontFamily: 'sans-serif',
    fontSize: 12,
    padding: [0, 0, 0, 0],
    overflow: 'none',
    formatter: '{b}',
  },
  emphasis: {
    focus: 'adjacency',
    lineStyle: {
      width: 10,
    },
  },
  autoCurveness: 20,
  animation: true,
  animationDuration: 500,
  animationEasing: 'cubicOut',
  tooltipConfiguration: { show: true, formatter: '{b}: {c}' },
  lineStyleConfiguration: { color: 'source', curveness: 0.1 },
  nodeSizeLeftLimit: 10,
  nodeSizeRightLimit: 60,
};
